### ISSUE TITLE
Tracking: Settings Screen

### ISSUE THREAD

**Issue by adzialocha** [p2panda/meli#35]
- [x] Basic Layout
- [x] Basic Screen Design
- [x] Switch language widget
- [x] Show basic system information (Android Version, CPU architecture etc., App Version)
- [x] https://github.com/p2panda/meli/issues/43

## Nice to have

- Show and burn private key
- Show aquadoggo logs
